import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';

import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import { NextIntlClientProvider } from 'next-intl';
import ShioriModalProvider from '@/modals/modal.provider'
import QueryProvider from '@/component/provider/QueryProvider';
import theme from '@/lib/theme';
import { notoSansMono, notoSansTC } from '@/lib/font';
import "./globals.css";
import { IntlClientProvider } from '@/i18n/provider';

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${notoSansMono.variable} ${notoSansTC.variable}`}>
        <NextIntlClientProvider>
          <IntlClientProvider>
            <MantineProvider theme={theme}>
              <QueryProvider>
                <ShioriModalProvider>
                  <Notifications position='top-right' />
                  {children}
                </ShioriModalProvider>
              </QueryProvider>
            </MantineProvider>
          </IntlClientProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
