import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';

import type { Metadata } from "next";
import { Noto_Sans_Mono, Noto_Sans_TC } from "next/font/google";
import { ColorSchemeScript, MantineProvider, mantineHtmlProps } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import ShioriModalProvider from '@/modals/modal.provider'
import QueryProvider from '@/component/provider/QueryProvider';
import theme from '@/lib/theme';
import "./globals.css";


const notoSansMono = Noto_Sans_Mono({
  variable: "--font-noto-sans-mono",
  subsets: ["latin"],
});

const notoSansTC = Noto_Sans_TC({
  variable: "--font-noto-sans-tc",
  preload: false,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className={`${notoSansMono.variable} ${notoSansTC.variable}`}>
        <MantineProvider theme={theme}>
          <QueryProvider>
            <ShioriModalProvider>
              <Notifications position='top-right' />
              {children}
            </ShioriModalProvider>
          </QueryProvider>
        </MantineProvider>
      </body>
    </html>
  );
}
